Repository org-SCAN/website, pull requests merged in 2022-10, with the labels that each got.

#223 [PR] Readme v2
  README.md
  img/portainer_add_edge.png
  img/portainer_home.png
Labels: documentation

#230 admin cant change his name -> corrected by changing the rule
  src/app/Rules/NotLastMoreImportantRole.php
Labels: bug

#231 [PR] Error EDIT person -> corrected
  src/app/Http/Controllers/RefugeeController.php
Labels: bug

#232 Can() in every policies + new navBar + Cyto model/policy
  src/app/Http/Controllers/CytoscapeController.php
  src/app/Models/Cytoscape.php
  src/app/Models/User.php
  src/app/Models/UserRole.php
  src/app/Policies/ApiLogPolicy.php
  src/app/Policies/CrewPolicy.php
  src/app/Policies/CytoscapePolicy.php
  src/app/Policies/DuplicatePolicy.php
  src/app/Policies/FieldPolicy.php
  src/app/Policies/LinkPolicy.php
  src/app/Policies/ListControlPolicy.php
  src/app/Policies/RefugeePolicy.php
  src/app/Policies/UserPolicy.php
  src/app/Providers/AuthServiceProvider.php
  src/resources/views/links/index.blade.php
  src/resources/views/links/show.blade.php
  src/resources/views/navigation-menu.blade.php
  src/resources/views/person/index.blade.php
Labels: enhancement

#241 [PR] adaptation de l api
  src/app/Http/Controllers/FieldsController.php
  src/app/Http/Controllers/LinkController.php
  src/app/Http/Controllers/RefugeeController.php
  src/app/Http/Requests/StoreLinkApiRequest.php
  src/app/Http/Requests/StoreRefugeeApiRequest.php
  src/app/Models/Field.php
  src/app/Models/ListControl.php
  src/app/Models/Refugee.php
  src/app/Models/Translation.php
  src/database/migrations/jsonDataset/config/lists_controls.json
  src/database/migrations/jsonDataset/fields.json
  src/database/seeders/FieldSeeder.php
  src/database/seeders/GlobalListControlSeeder.php
  src/resources/views/fields/edit.blade.php
Labels: enhancement

#250 [PR] Feature/issue 245 new feature allow admin to handle api request from users view
  src/app/Models/Permission.php
  src/app/Policies/GlobalPolicy.php
  src/resources/views/user/show.blade.php
Labels: enhancement

#256 [PR] Feature/issue 222 new feature upgrade filtering options
  src/app/Http/Controllers/FieldsController.php
  src/app/Http/Controllers/LinkController.php
  src/app/Http/Requests/StoreFieldRequest.php
  src/app/Http/Requests/UpdateFieldRequest.php
  src/app/Models/Link.php
  src/resources/views/links/create.blade.php
  src/resources/views/links/index.blade.php
  src/resources/views/navigation-menu.blade.php
  src/resources/views/person/index.blade.php
  src/resources/views/person/show.blade.php
  src/routes/web.php
Labels: bug, enhancement

#258 [PR] New Nav Bar + Coussin list creation + multi add + update role editor
  src/app/Http/Controllers/ListControlController.php
  src/app/Http/Requests/StoreListControlFieldsRequest.php
  src/app/Models/Field.php
  src/app/Models/Permission.php
  src/app/Providers/RouteServiceProvider.php
  src/config/fortify.php
  src/database/migrations/jsonDataset/roles.json
  src/resources/views/errors/403.blade.php
  src/resources/views/fields/show.blade.php
  src/resources/views/lists_control/create.blade.php
  src/resources/views/lists_control/create_fields.blade.php
  src/resources/views/navigation-menu.blade.php
  src/resources/views/vendor/jetstream/components/dropdown-link.blade.php
  src/resources/views/vendor/jetstream/components/dropdown.blade.php
  src/resources/views/vendor/jetstream/components/welcome.blade.php
  src/routes/web.php
Labels: enhancement

#280 [PR] Fix several thing regarding the meeting with JP
  src/app/Http/Controllers/CrewController.php
  src/app/Http/Controllers/FieldsController.php
  src/app/Http/Controllers/ManageUsersController.php
  src/app/Http/Requests/StoreFieldRequest.php
  src/app/Http/Requests/StoreUserRequest.php
  src/app/Http/Requests/addUserToCrewRequest.php
  src/app/Models/Crew.php
  src/resources/views/crew/create.blade.php
  src/resources/views/crew/index.blade.php
  src/resources/views/crew/show.blade.php
  src/resources/views/errors/404.blade.php
  src/resources/views/fields/create.blade.php
  src/resources/views/navigation-menu.blade.php
  src/resources/views/roles/create.blade.php
  src/resources/views/roles/edit.blade.php
  src/resources/views/user/create.blade.php
  src/routes/web.php
Labels: bug, enhancement

#281 Master/dev Fix issues regarding the meeting with JP
  src/app/Http/Controllers/CrewController.php
  src/app/Http/Controllers/FieldsController.php
  src/app/Http/Controllers/ManageUsersController.php
  src/app/Http/Requests/StoreFieldRequest.php
  src/app/Http/Requests/StoreUserRequest.php
  src/app/Http/Requests/addUserToCrewRequest.php
  src/app/Models/Crew.php
  src/resources/views/crew/create.blade.php
  src/resources/views/crew/index.blade.php
  src/resources/views/crew/show.blade.php
  src/resources/views/errors/404.blade.php
  src/resources/views/fields/create.blade.php
  src/resources/views/navigation-menu.blade.php
  src/resources/views/roles/create.blade.php
  src/resources/views/roles/edit.blade.php
  src/resources/views/user/create.blade.php
  src/routes/web.php
Labels: enhancement

#284 static role coloration
  src/app/Http/Controllers/CytoscapeController.php
  src/package.json
  src/public/js/cytoscape/index.js
  src/resources/js/cytoscape/index.js
  src/resources/views/cytoscape/index.blade.php
  src/resources/views/vendor/jetstream/components/welcome.blade.php
Labels: enhancement

#287 Master/dev -> colored roles
  src/app/Http/Controllers/CytoscapeController.php
  src/package.json
  src/public/js/cytoscape/index.js
  src/resources/js/cytoscape/index.js
  src/resources/views/cytoscape/index.blade.php
  src/resources/views/vendor/jetstream/components/welcome.blade.php
Labels: enhancement

#291 new logo for auth
  src/resources/views/vendor/jetstream/components/authentication-card-logo.blade.php
Labels: enhancement
