Repository org-SCAN/website, pull requests merged in 2022-11, with the labels that each got.

#296 Feature/issue 150 Add Event V0.5 feature
  src/app/Console/Commands/updateList.php
  src/app/Console/Commands/updatePermissions.php
  src/app/Http/Controllers/CrewController.php
  src/app/Http/Controllers/CytoscapeController.php
  src/app/Http/Controllers/EventController.php
  src/app/Http/Controllers/LinkController.php
  src/app/Http/Requests/StoreCrewRequest.php
  src/app/Http/Requests/StoreEventRequest.php
  src/app/Http/Requests/StoreLinkRequest.php
  src/app/Http/Requests/StoreListControlRequest.php
  src/app/Http/Requests/UpdateCrewRequest.php
  src/app/Http/Requests/UpdateEventRequest.php
  src/app/Http/Requests/UpdateFieldRequest.php
  src/app/Models/Crew.php
  src/app/Models/Event.php
  src/app/Models/ListControl.php
  src/app/Models/ListCountry.php
  src/app/Models/ListEventType.php
  src/app/Models/Permission.php
  src/app/Models/Refugee.php
  src/app/Policies/EventPolicy.php
  src/app/Policies/FieldPolicy.php
  src/app/Rules/PersonHasEvent.php
  src/config/jetstream.php
  src/database/factories/EventFactory.php
  src/database/migrations/2022_03_07_160104_create_events_table.php
  src/database/migrations/2022_10_27_142309_create_list_event_types_table.php
  src/database/migrations/jsonDataset/config/lists_controls.json
  src/database/migrations/jsonDataset/listeventtypes.json
  src/database/migrations/jsonDataset/roles.json
  src/database/seeders/DatabaseSeeder.php
  src/database/seeders/ListControlSeeder.php
  src/database/seeders/ListEventTypeSeeder.php
  src/database/seeders/PermissionSeeder.php
  src/resources/js/cytoscape/index.js
  src/resources/markdown/terms.md
  src/resources/views/cytoscape/index.blade.php
  src/resources/views/event/create.blade.php
  src/resources/views/event/edit.blade.php
  src/resources/views/event/index.blade.php
  src/resources/views/event/show.blade.php
  src/resources/views/links/create.blade.php
  src/resources/views/lists_control/define_displayed_value.blade.php
  src/resources/views/navigation-menu.blade.php
  src/routes/web.php
Labels: New feature, bug, enhancement

#302 [PR] Feature/issue 182 ressource source
  src/app/Http/Controllers/SourceController.php
  src/app/Http/Requests/StoreSourceRequest.php
  src/app/Http/Requests/UpdateSourceRequest.php
  src/app/Models/ListSourceType.php
  src/app/Models/Permission.php
  src/app/Models/Source.php
  src/app/Policies/SourcePolicy.php
  src/database/factories/SourceFactory.php
  src/database/migrations/2022_11_03_084914_create_sources_table.php
  src/database/migrations/2022_11_03_095042_create_list_source_types_table.php
  src/database/migrations/jsonDataset/config/lists_controls.json
  src/database/migrations/jsonDataset/listsourcetypes.json
  src/database/seeders/DatabaseSeeder.php
  src/database/seeders/ListSourceTypeSeeder.php
  src/database/seeders/SourceSeeder.php
  src/resources/views/event/edit.blade.php
  src/resources/views/navigation-menu.blade.php
  src/resources/views/sources/create.blade.php
  src/resources/views/sources/edit.blade.php
  src/resources/views/sources/index.blade.php
  src/resources/views/sources/show.blade.php
  src/routes/web.php
Labels: New feature

#304 [PR] Feature/issue 274 new feature send email with the access when creating an account
  src/app/Actions/Fortify/PasswordValidationRules.php
  src/app/Http/Controllers/ManageUsersController.php
  src/app/Http/Requests/StoreUserRequest.php
  src/app/Notifications/InviteUserNotification.php
  src/app/Policies/UserPolicy.php
  src/app/Providers/AuthServiceProvider.php
  src/config/auth.php
  src/config/fortify.php
  src/database/seeders/DatabaseSeeder.php
  src/resources/views/errors/401.blade.php
  src/resources/views/errors/419.blade.php
  src/resources/views/errors/429.blade.php
  src/resources/views/errors/500.blade.php
  src/resources/views/errors/503.blade.php
  src/resources/views/errors/layout.blade.php
  src/resources/views/errors/minimal.blade.php
  src/resources/views/user/create.blade.php
  src/resources/views/user/show.blade.php
  src/resources/views/vendor/mail/html/button.blade.php
  src/resources/views/vendor/mail/html/footer.blade.php
  src/resources/views/vendor/mail/html/header.blade.php
  src/resources/views/vendor/mail/html/layout.blade.php
  src/resources/views/vendor/mail/html/message.blade.php
  src/resources/views/vendor/mail/html/panel.blade.php
  src/resources/views/vendor/mail/html/subcopy.blade.php
  src/resources/views/vendor/mail/html/table.blade.php
  src/resources/views/vendor/mail/html/themes/default.css
  src/resources/views/vendor/mail/text/button.blade.php
  src/resources/views/vendor/mail/text/footer.blade.php
  src/resources/views/vendor/mail/text/header.blade.php
  src/resources/views/vendor/mail/text/layout.blade.php
  src/resources/views/vendor/mail/text/message.blade.php
  src/resources/views/vendor/mail/text/panel.blade.php
  src/resources/views/vendor/mail/text/subcopy.blade.php
  src/resources/views/vendor/mail/text/table.blade.php
  src/routes/web.php
Labels: New feature

#305 [PR] Feature/issue 303 new feature quick add person as a source
  src/app/Http/Controllers/RefugeeController.php
  src/app/Policies/GlobalPolicy.php
  src/resources/views/person/create.blade.php
  src/resources/views/person/edit.blade.php
  src/resources/views/person/show.blade.php
Labels: bug, enhancement

#321 [PR] fix(field): Spinner Java type
  .gitignore
  src/app/Models/Field.php
  src/resources/views/person/create.blade.php
Labels: bug

#323 [PR] fix(field): Spinner Java type (edit field)
  src/app/Http/Controllers/FieldsController.php
  src/app/Models/Event.php
  src/app/Models/Field.php
  src/app/Models/Source.php
Labels: bug

#320 [PR] Add new tests to USER
  .github/workflows/laravel.yml
  src/app/Http/Controllers/ManageUsersController.php
  src/app/Models/User.php
  src/app/Policies/GlobalPolicy.php
  src/app/Policies/UserPolicy.php
  src/app/Traits/ClearProperties.php
  src/tests/Feature/PermissionsTest.php
  src/tests/Feature/UserTest.php
  src/tests/TestCase.php
Labels: enhancement

#331 [PR] Feature/issue 315 new feature new api feature link
  src/app/Http/Controllers/LinkController.php
  src/app/Models/Crew.php
  src/app/Models/Link.php
  src/routes/api.php
  src/tests/Feature/Event.php
  src/tests/Feature/LinkTest.php
  src/tests/Feature/PersonTest.php
  src/tests/TestCase.php
Labels: enhancement

#333 [PR] Feature/issue 297 new feature live wire components
  src/app/Http/Livewire/Forms/Form.php
  src/app/Http/Livewire/Forms/FormDoubleDropdown.php
  src/database/migrations/jsonDataset/fields.json
  src/resources/views/fields/create.blade.php
  src/resources/views/fields/edit.blade.php
  src/resources/views/livewire/forms/form-checkbox.blade.php
  src/resources/views/livewire/forms/form-date.blade.php
  src/resources/views/livewire/forms/form-double-dropdown.blade.php
  src/resources/views/livewire/forms/form-number.blade.php
  src/resources/views/livewire/forms/form-text.blade.php
  src/resources/views/person/create.blade.php
Labels: enhancement

#336 [PR] Feature/issue 329 new feature basic duplicate section
  src/app/Console/Commands/DuplicateCommand.php
  src/app/Console/Kernel.php
  src/app/Http/Controllers/DuplicateController.php
  src/app/Http/Controllers/FieldsController.php
  src/app/Http/Controllers/ManageUsersController.php
  src/app/Http/Controllers/RefugeeController.php
  src/app/Models/CommandRun.php
  src/app/Models/Duplicate.php
  src/app/Notifications/InviteUserNotification.php
  src/app/Policies/DuplicatePolicy.php
  src/database/factories/CommandRunFactory.php
  src/database/migrations/2022_11_15_135936_create_command_runs_table.php
  src/database/migrations/2022_11_15_143153_duplicates.php
  src/database/seeders/LinkSeeder.php
  src/database/seeders/RefugeeSeeder.php
  src/resources/views/duplicate/index.blade.php
  src/routes/web.php
  src/tests/Feature/DuplicateTest.php
  src/tests/Feature/UserTest.php
Labels: New feature, bug, enhancement

#338 [PR] Rename Edit -> Save + relations with date
  src/app/Http/Controllers/LinkController.php
  src/app/Http/Requests/StoreLinkRequest.php
  src/app/Http/Requests/UpdateLinkRequest.php
  src/app/Models/Link.php
  src/resources/views/crew/edit.blade.php
  src/resources/views/event/create.blade.php
  src/resources/views/event/edit.blade.php
  src/resources/views/fields/create.blade.php
  src/resources/views/fields/edit.blade.php
  src/resources/views/links/create.blade.php
  src/resources/views/links/edit.blade.php
  src/resources/views/links/index.blade.php
  src/resources/views/lists_control/create.blade.php
  src/resources/views/lists_control/edit.blade.php
  src/resources/views/person/create.blade.php
  src/resources/views/person/edit.blade.php
  src/resources/views/roles/edit.blade.php
  src/resources/views/sources/create.blade.php
  src/resources/views/sources/edit.blade.php
  src/resources/views/user/edit.blade.php
Labels: enhancement

#343 [PR] Feature/issue 282 new feature bilateral relations
  .github/workflows/laravel.yml
  src/app/Console/Commands/UpdateList.php
  src/app/Http/Controllers/CytoscapeController.php
  src/app/Http/Controllers/LinkController.php
  src/app/Http/Requests/StoreLinkRequest.php
  src/app/Http/Requests/UpdateLinkRequest.php
  src/app/Models/Event.php
  src/app/Models/Link.php
  src/app/Models/ListControl.php
  src/app/Models/Refugee.php
  src/app/Rules/RelationDoesNotAlreadyExist.php
  src/composer.json
  src/config/database.php
  src/database/factories/LinkFactory.php
  src/database/migrations/2022_11_18_154211_add_type_to_list_relations_table.php
  src/database/migrations/2022_11_21_111017_rename_relation_to_relation_id_to_links.php
  src/database/migrations/jsonDataset/listrelations.json
  src/database/seeders/GlobalListControlSeeder.php
  src/resources/views/fields/edit.blade.php
  src/resources/views/links/create.blade.php
  src/resources/views/links/edit.blade.php
  src/resources/views/links/index.blade.php
  src/tests/Feature/LinkTest.php
Labels: New feature, enhancement

#345 [PR] hotfix(cytoscape): Cytoscape 500 errror
  src/app/Http/Controllers/CytoscapeController.php
Labels: bug

#346 hotfix(cytoscape): Cytoscape 500 errror
  src/app/Http/Controllers/CytoscapeController.php
Labels: bug

#355 Feature/issue 314 new feature new api feature list
  src/app/Http/Controllers/ListControlController.php
  src/app/Policies/RefugeePolicy.php
  src/routes/api.php
Labels: enhancement
