Repository org-SCAN/website, pull requests merged in 2023-01, with the labels that each got.

#388 Feature/issue 350 new feature frontend component for localisation
  src/app/Http/Controllers/EventController.php
  src/app/Http/Controllers/RefugeeController.php
  src/app/Http/Livewire/CreateFormChooseField.php
  src/app/Http/Livewire/Forms/Coordinates.php
  src/app/Http/Livewire/Forms/Form.php
  src/app/Http/Requests/StoreEventRequest.php
  src/app/Http/Requests/StoreRefugeeRequest.php
  src/app/Http/Requests/UpdateEventRequest.php
  src/app/Http/Requests/UpdateRefugeeRequest.php
  src/app/Interface/DataTypeModel.php
  src/app/Models/Field.php
  src/app/Models/Refugee.php
  src/composer.json
  src/config/vendor/maps.php
  src/database/factories/EventFactory.php
  src/database/migrations/2022_03_07_160104_create_events_table.php
  src/database/migrations/jsonDataset/config/lists_controls.json
  src/database/migrations/jsonDataset/listdatatypes.json
  src/public/vendor/maps/css/index.css
  src/public/vendor/maps/js/index.js
  src/public/vendor/maps/js/index.js.LICENSE.txt
  src/public/vendor/maps/mix-manifest.json
  src/resources/views/event/create.blade.php
  src/resources/views/event/edit.blade.php
  src/resources/views/event/show.blade.php
  src/resources/views/layouts/app.blade.php
  src/resources/views/livewire/forms/form-coordinates.blade.php
  src/resources/views/livewire/forms/form-date.blade.php
  src/resources/views/livewire/forms/show/coordinates.blade.php
  src/resources/views/person/show.blade.php
Labels: New feature

#389 [PR] Feature/issue 79 import csv files
  src/.gitignore
  src/app/Http/Controllers/CrewController.php
  src/app/Http/Controllers/LinkController.php
  src/app/Http/Controllers/RefugeeController.php
  src/app/Http/Livewire/Forms/Show.php
  src/app/Http/Requests/FileRefugeeRequest.php
  src/app/Http/Requests/JsonFileRefugeeRequest.php
  src/app/Imports/RefugeesImport.php
  src/app/Models/ApiLog.php
  src/app/Models/Duplicate.php
  src/app/Models/Refugee.php
  src/composer.json
  src/config/excel.php
  src/resources/views/livewire/forms/show/checkbox.blade.php
  src/resources/views/person/create_from_json.blade.php
  src/resources/views/person/index.blade.php
  src/routes/web.php
Labels: New feature, enhancement

#393 [PR] fix(nav-bar): update
  src/resources/views/navigation-menu.blade.php
  src/resources/views/sources/show.blade.php
Labels: bug

#395 [PR] bug(Refugee): Import from csv
  .idea/php.xml
  src/app/Http/Controllers/ManageUsersController.php
  src/app/Http/Requests/FileRefugeeRequest.php
  src/public/css/app.css
  src/public/js/cytoscape/cytoscape.js
  src/public/js/cytoscape/vendor.js
  src/public/js/vendor.js
  src/public/js/vendor.js.LICENSE.txt
  src/public/mix-manifest.json
Labels: bug
